# Generated by Django 2.2.5 on 2022-05-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0003_auto_20220419_0647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='takeappointment',
            old_name='message',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='takeappointment',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='takeappointment',
            name='id',
        ),
        migrations.AlterField(
            model_name='takeappointment',
            name='user',
            field=models.CharField(max_length=100, primary_key='user', serialize=False),
        ),
    ]
