# Generated by Django 2.2.5 on 2022-05-09 22:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0004_auto_20220509_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='takeappointment',
            name='id',
            field=models.AutoField(auto_created=True, default=datetime.datetime(2022, 5, 9, 22, 32, 25, 484357, tzinfo=utc), primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='takeappointment',
            name='email',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='takeappointment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
