# Generated by Django 2.2.5 on 2022-05-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0005_auto_20220510_0432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='image',
        ),
        migrations.RemoveField(
            model_name='takeappointment',
            name='id',
        ),
        migrations.AlterField(
            model_name='takeappointment',
            name='user',
            field=models.CharField(max_length=100, primary_key='user', serialize=False),
        ),
    ]
