# Generated by Django 2.2.5 on 2022-05-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0006_auto_20220510_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takeappointment',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
