# Generated by Django 4.0.2 on 2022-03-30 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=50)),
                ('date_of_birth', models.CharField(max_length=50)),
                ('date_of_joining', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=50)),
                ('team', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('category', models.CharField(choices=[('YAC', 'Ac'), ('NAC', 'Non-Ac'), ('DEL', 'Deluex'), ('KIN', 'King'), ('QUE', 'Queen'), ('STDIOU', 'Stduio'), ('HTR', 'Hollywood-Twin-Room'), ('ES', 'Executive'), ('MS', 'MiniSuite'), ('PS', 'PresidentialSuite'), ('AP', 'Apartments'), ('CR', 'ConnectingRooms'), ('MR', 'MurphyRooms'), ('AR', 'Accessible'), ('CN', 'Cabana'), ('ADR', 'AdjoiningRoom'), ('VIL', 'Villa'), ('EF', 'ExecutiveRoom'), ('NSM', 'Non-SmokingRoom')], max_length=6)),
                ('beds', models.IntegerField()),
                ('desc', models.TextField()),
                ('capacity', models.IntegerField()),
                ('image', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='VacinationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacinationCirtificateNum', models.CharField(max_length=12)),
                ('totalDose', models.IntegerField()),
                ('covidTest', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('DateofBirth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDetected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.employee')),
            ],
        ),
        migrations.CreateModel(
            name='BookingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
