# Generated by Django 4.0.2 on 2022-03-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.TextField(),
        ),
    ]
