# Generated by Django 4.0.2 on 2022-02-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('YAC', 'AC'), ('NAC', 'NON-AC'), ('DEL', 'DELUXE'), ('KIN', 'KING'), ('QUE', 'QUEEN'), ('STDIOU', 'STUDIO'), ('ES', 'Executive'), ('MS', 'MiniSuite'), ('PS', 'PresidentialSuite'), ('AP', 'Apartments'), ('CR', 'ConnectingRooms'), ('MR', 'MurphyRooms'), ('AR', 'Accessible'), ('CN', 'Cabana'), ('ADR', 'AdjoiningRoom'), ('VIL', 'Villa'), ('EF', 'ExecutiveRoom'), ('NSM', 'Non-SmokingRoom')], max_length=6),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.CharField(max_length=400),
        ),
    ]
