# Generated by Django 4.0.2 on 2022-02-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_modeli'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcn', models.CharField(max_length=12)),
                ('td', models.ImageField(upload_to='')),
                ('ct', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Modeli',
        ),
    ]
