# Generated by Django 2.2.5 on 2022-04-19 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_auto_20220419_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetected',
            name='emp_id',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='EmployeeDetected',
        ),
    ]
