# Generated by Django 2.2.5 on 2022-05-05 14:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_auto_20220428_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('rate', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='bookingroom',
            name='payment_status',
            field=models.CharField(choices=[('COM', 'PAYMENT_COMPLETE'), ('INC', 'PAYMENT_INCOMPLETE'), ('PAR', 'PAYMENT_PARTIALLY_COMPLETE')], default=datetime.datetime(2022, 5, 5, 14, 15, 37, 551094, tzinfo=utc), max_length=3),
            preserve_default=False,
        ),
    ]
