# Generated by Django 2.2.5 on 2022-05-09 20:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_auto_20220510_0252'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='roomcategory',
            name='rate',
            field=models.FloatField(default=datetime.datetime(2022, 5, 9, 20, 59, 36, 52802, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roomcategory',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
