# Generated by Django 2.2.5 on 2022-05-10 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_auto_20220510_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingroom',
            name='payment_status',
        ),
    ]
