# Generated by Django 2.2.5 on 2022-05-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeRec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detected',
            name='photo',
            field=models.ImageField(default='employeeRec/facerec/detected/noimg.png', upload_to='detected/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(max_length=60, primary_key=True, serialize=False),
        ),
    ]
