# Generated by Django 2.2.5 on 2022-05-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeRec', '0003_auto_20220509_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
